import Aside from '@/components/common/aside/Aside';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={inter.className} lang="en">
      <body className="flex w-screen overflow-x-hidden-hidden">
        <Aside />
        <div>
          <header className="w-full bg-yellow-300 flex justify-between">
            <h1>header</h1>
            <h2>sdfdsf</h2>
          </header>
          <main className="bg-slate-300">{children}</main>
        </div>
      </body>
    </html>
  );
}
